- name: Package installed test
  stat:
    path: '/var/lib/pkgtools/packages/{{ pkg_basename }}'
  register: package_result

- name: Remove Package
  shell: '/sbin/removepkg {{ pkg_basename }}'
  register: package_log
  when: package_result.stat.exists is true
  become: true

- name: Show log
  debug:
    msg: "{{ package_log }}"

- name: Remove temp file
  file:
    path: '/tmp/{{ pkg_basename }}.txz'
    state: absent
  become: true