---

- name: slackware-k8s install playbook
  gather_facts: false
  hosts: nodes

  vars:
    k8s_core_packages: 
      - containerd-1.7.16-x86_64-1
      - crictl-1.31.1-x86_64-1
      - cni-plugins-1.5.1-x86_64-1
      - runc-1.1.14-x86_64-1
      - kubelet-1.31.0-x86_64-1
      - kubeadm-1.31.0-x86_64-2
      - nerdctl-1.7.7-x86_64-1
    k8s_control_packages:
      - kubectl-1.31.0-x86_64-2

  tasks:
    - name: DEBUG package list
      debug:
        var: k8s_core_packages
    
    - name: Install core packages
      include_tasks: installpkg.yaml
      loop: "{{ k8s_core_packages }}"
      when: pkg_basename is defined
      vars:
        pkg_basename: '{{ item }}'

    - name: Install control core packages
      include_tasks: installpkg.yaml
      loop: "{{ k8s_control_packages }}"
      when:
        - '"control" in group_names'
        - pkg_basename is defined 
      vars:
        pkg_basename: '{{ item }}'

    - name: Install rc.containerd file
      copy:
        src: rc.containerd
        dest: /etc/rc.d/rc.containerd
      become: true

    - name: Set permissions on rc.containerd
      file:
        path: /etc/rc.d/rc.containerd
        owner: root
        group: root
        mode: '0744'
      become: true

    - name: Install rc.kubelet file
      copy:
        src: rc.kubelet
        dest: /etc/rc.d/rc.kubelet
      become: true

    - name: Set permissions on rc.kubelet
      file:
        path: /etc/rc.d/rc.kubelet
        owner: root
        group: root
        mode: '0744'
      become: true

    - name: Set permissions on rc.ip_forward
      file:
        path: /etc/rc.d/rc.ip_forward
        state: touch
        mode: u+x
      become: true
      
    - name: Ensure sudo group has sudo privileges without password
      lineinfile:
        dest: /etc/ntp.conf
        state: present
        regexp: "^server"
        line: "server 10.1.31.1 iburst"
      become: true

    - name: Set permissions on rc.ip_forward
      file:
        path: /etc/rc.d/rc.ntpd
        state: touch
        mode: a+x
      become: true
