---

- name: slackware package deployment playbook
  gather_facts: true
  hosts: nodes

  vars:
    tst_basename: crictl-1.31.1-x86_64-1
    pkg_basename: runc-1.1.14-x86_64-1

  tasks:
    - name: start
      script:
        cmd: /etc/rc.d/rc.containerd start
      become: true

