---

- name: slackware incus install playbook
  gather_facts: false
  hosts: nodes

  vars:
    incus_packages: 
      - raft-0.22.1-x86_64-1_SBo
      - cowsql-1.15.9-x86_64-1_SBo
      - incus-6.16-x86_64-1_SBo
      - skopeo-1.20.0-x86_64-1_SBo
    support_packages:
      - google-go-lang-1.25.0-x86_64-1
    conflict_packages:
      - gcc-go-15.2.0-x86_64-1
      
  tasks:
    - name: DEBUG package list
      debug:
        var: incus_packages

    - name: Remove conflict packages
      include_tasks: ../slackware/removepkg.yaml
      loop: "{{ conflict_packages }}"
      when: pkg_basename is defined
      vars:
        pkg_basename: '{{ item }}' 

    - name: Install core packages
      include_tasks: ../slackware/installpkg.yaml
      loop: "{{ incus_packages }}"
      when: pkg_basename is defined
      vars:
        pkg_basename: '{{ item }}'
        pkg_source_dir: 'files/'

    - name: Install support packages
      include_tasks: ../slackware/installpkg.yaml
      loop: "{{ support_packages }}"
      when: pkg_basename is defined
      vars:
        pkg_basename: '{{ item }}'
        pkg_source_dir: 'files/'

    - name: Install rc.incusd file
      copy:
        src: rc.d/rc.incusd
        dest: /etc/rc.d/rc.incusd
      become: true

    - name: Set permissions on rc.containerd
      file:
        path: /etc/rc.d/rc.incusd
        owner: root
        group: root
        mode: '0744'
      become: true

    - name: Install default config file
      copy:
        src: default/incus
        dest: /etc/default/incus
      become: true

    - name: Set permissions on default config
      file:
        path: /etc/default/incus
        owner: root
        group: root
        mode: '0644'
      become: true

    - name: Configure CGROUPS2 (on next reboot)_
      lineinfile:
        path: /etc/default/cgroups
        regexp: '^CGROUPS_VERSION='
        line: CGROUPS_VERSION=2
      become: true


    - name: subgid allocation
      lineinfile:
        path: /etc/subgid
        regexp: '^root:'
        line: root:1000000:1000000000
        state: present
        create: true
      become: true

    - name: subuid allocation
      lineinfile:
        path: /etc/subuid
        regexp: '^root:'
        line: root:1000000:1000000000
        state: present
        create: true
      become: true

     
    - name: Set permissions to enable IP forwarding
      file:
        path: /etc/rc.d/rc.ip_forward
        owner: root
        group: root
        mode: '0744'
      become: true
