---

- name: slackware ovn install playbook
  gather_facts: false
  hosts: clusternode

  tasks:
    - name: Set permissions on rc.openvswitch
      file:
        path: /etc/rc.d/rc.openvswitch
        owner: root
        group: root
        mode: '0744'
      become: true

    - name: Set permissions on rc.ovn-host
      file:
        path: /etc/rc.d/rc.ovn-host
        owner: root
        group: root
        mode: '0744'
      become: true

    - name: Set permissions on rc.ovn-central
      file:
        path: /etc/rc.d/rc.ovn-central
        owner: root
        group: root
        mode: '0744'
      become: true